server:
  port: 9999

spring:
  application:
    name: user-client

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}

#设置负载
#第一个参数为被调用服务的serviceId
product-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
