spring:
  application:
    name: eureka-client-8888

server:
  port: 8888

eureka:
  client:
    service-url:
      #设置默认访问地址
      defaultZone: http://localhost:8761/eureka
      #禁止自我注册
      register-with-eureka: false
      #关闭作为客户端时从eureka server获取服务信息
      fetch-registry: false
