spring:
  application:
    name: eureka-server-8761

server:
  port: 8761

eureka:
  client:
    service-url:
      #\u8BBE\u7F6E\u9ED8\u8BA4\u8BBF\u95EE\u5730\u5740
      defaultZone: http://localhost:8761/eureka
    #\u7981\u6B62\u81EA\u6211\u6CE8\u518C
    register-with-eureka: false
    #\u5173\u95ED\u4F5C\u4E3A\u5BA2\u6237\u7AEF\u65F6\u4ECEeureka server\u83B7\u53D6\u670D\u52A1\u4FE1\u606F
    fetch-registry: false
